// <auto-generated />
using System;
using Lending.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Lending.Infrastructure.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    [Migration("20260819033017_AddRepaymentNote")]
    partial class AddRepaymentNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("facility_reference_seq");

            modelBuilder.Entity("Lending.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp_utc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Lending.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registration_number");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "LegalName", "RegistrationNumber", "Industry" });

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_name");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_companies_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex(new[] { "Name" }, "ix_companies_name_trgm")
                        .HasDatabaseName("ix_companies_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_companies_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_companies_name_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Lending.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("annual_interest_rate");

                    b.Property<decimal>("CommitmentAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commitment_amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("outstanding_principal");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference");

                    b.Property<string>("RepaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("repayment_type");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Reference" });

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_facilities");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_facilities_company_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_facilities_reference");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_facilities_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_facilities_status");

                    b.HasIndex(new[] { "Reference" }, "ix_facilities_reference_trgm")
                        .HasDatabaseName("ix_facilities_reference_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Reference" }, "ix_facilities_reference_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Reference" }, "ix_facilities_reference_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("Lending.Domain.Entities.Repayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<decimal>("InterestApplied")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest_applied");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversal");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<decimal>("PrincipalApplied")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal_applied");

                    b.Property<Guid?>("ReversedByRepaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by_repayment_id");

                    b.Property<Guid?>("ReversesRepaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_repayment_id");

                    b.HasKey("Id")
                        .HasName("pk_repayments");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_repayments_facility_id");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("ix_repayments_payment_date");

                    b.HasIndex("ReversesRepaymentId")
                        .HasDatabaseName("ix_repayments_reverses_repayment_id");

                    b.ToTable("repayments", (string)null);
                });

            modelBuilder.Entity("Lending.Domain.Entities.RepaymentScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<decimal>("InterestDue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest_due");

                    b.Property<decimal>("InterestPaid")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest_paid");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<decimal>("PrincipalDue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal_due");

                    b.Property<decimal>("PrincipalPaid")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal_paid");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remaining_balance");

                    b.HasKey("Id")
                        .HasName("pk_schedule_items");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_schedule_items_due_date");

                    b.HasIndex("FacilityId", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_items_facility_id_period");

                    b.ToTable("schedule_items", (string)null);
                });

            modelBuilder.Entity("Lending.Domain.Entities.Facility", b =>
                {
                    b.HasOne("Lending.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_facilities_companies_company_id");
                });

            modelBuilder.Entity("Lending.Domain.Entities.Repayment", b =>
                {
                    b.HasOne("Lending.Domain.Entities.Facility", null)
                        .WithMany("Repayments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_repayments_facilities_facility_id");

                    b.OwnsMany("Lending.Domain.Entities.RepaymentAllocation", "Allocations", b1 =>
                        {
                            b1.Property<Guid>("RepaymentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<decimal>("Interest")
                                .HasColumnType("numeric");

                            b1.Property<int>("Period")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Principal")
                                .HasColumnType("numeric");

                            b1.HasKey("RepaymentId", "Id")
                                .HasName("pk_repayments");

                            b1.ToTable("repayments");

                            b1.ToJson("allocations");

                            b1.WithOwner()
                                .HasForeignKey("RepaymentId")
                                .HasConstraintName("fk_repayments_repayments_repayment_id");
                        });

                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Lending.Domain.Entities.RepaymentScheduleItem", b =>
                {
                    b.HasOne("Lending.Domain.Entities.Facility", null)
                        .WithMany("Schedule")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_items_facilities_facility_id");
                });

            modelBuilder.Entity("Lending.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Repayments");

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
